apiVersion: v1
kind: ReplicationController
metadata:
  name: rishi-rc
spec:
  replicas: 5
  selector:
    app: rishijavaaap
  template:
    metadata:
      labels: 
        app: rishijavaaap
    spec:
      containers:
      - name: myapp
        image: nginx
        ports:
        - containerPort: 80

