apiVersion: v1
kind: ReplicationController
metadata:
  name: rishi-rc
spec:
  replicas: 5
  selector:
    app: rishijavaaap
    version: 2.6.1
  template:
    metadata:
      labels: 
        app: rishijavaaap
        version: 2.6.1
    spec:
      containers:
      - name: myapp
        image: maha4iac/mahalogin:1
        ports:
        - containerPort: 8080

